

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
# # VALUES ARE NOT CORRECT !
# EffortJointInterface_J1_controller:
#   type: effort_controllers/JointPositionController
#   joint: j0
#   pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

# EffortJointInterface_J2_controller:
#   type: effort_controllers/JointPositionController
#   joint: j1
#   pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

# EffortJointInterface_J3_controller:
#   type: effort_controllers/JointPositionController
#   joint: j2
#   pid: {p: 800.0, i: 10, d: 5.0, i_clamp_min: -10000, i_clamp_max: 10000}

# EffortJointInterface_J4_controller:
#   type: effort_controllers/JointPositionController
#   joint: j3
#   pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

# Forward Position Controllers ---------------------------------------
PositionJointInterface_J1_controller:
  type: position_controllers/JointPositionController
  joint: j0

PositionJointInterface_J2_controller:
  type: position_controllers/JointPositionController
  joint: j1
  
PositionJointInterface_J3_controller:
  type: position_controllers/JointPositionController
  joint: j2
  
PositionJointInterface_J4_controller:
  type: position_controllers/JointPositionController
  joint: j3


# # Effort Position Controllers ---------------------------------------
# EffortJointInterface_trajectory_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - j0
#     - j1
#     - j2
#     - j3

#   gains:
#     j0: {p: 500,  d: 30, i: 15, i_clamp: 30}
#     j1: {p: 200,  d: 10, i: 10, i_clamp: 30}
#     j2: {p: 65,  d: 10, i: 15, i_clamp: 30}
#     j3: {p: 31,  d: 7, i: 12, i_clamp: 30}

#   constraints:
#     goal_time: 0.5                   # Override default

#   state_publish_rate:  25            # Override default
#   action_monitor_rate: 30            # Override default
#   stop_trajectory_duration: 0        # Override default

# # Forward Velocity Controllers ---------------------------------------
# VelocityJointInterface_J1_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: j0
  
# VelocityJointInterface_J2_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: j1
  
# VelocityJointInterface_J3_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: j2
  
# VelocityJointInterface_J4_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: j3
  
# # Forward Position Controllers ---------------------------------------
# PositionJointInterface_trajectory_controller:
#   type: position_controllers/JointTrajectoryController
#   joints: 
#     - j0
#     - j1
#     - j2
#     - j3

#   constraints:
#     goal_time: 0.5                   # Override default

#   state_publish_rate:  25            # Override default
#   action_monitor_rate: 30            # Override default
#   stop_trajectory_duration: 0        # Override default

# # Forward Velocity Controllers ---------------------------------------
# VelocityJointInterface_trajectory_controller:
#   type: velocity_controllers/JointTrajectoryController
#   joints: 
#     - j0
#     - j1
#     - j2
#     - j3
    
#     # VALUES ARE NOT CORRECT !
#   gains:
#     j0: {p: 500,  d: 30, i: 15, i_clamp: 30}
#     j1: {p: 200,  d: 10, i: 10, i_clamp: 30}
#     j2: {p: 65,  d: 10, i: 15, i_clamp: 30}
#     j3: {p: 31,  d: 7, i: 12, i_clamp: 30}

#   constraints:
#     goal_time: 0.5                   # Override default

#   state_publish_rate:  25            # Override default
#   action_monitor_rate: 30            # Override default
#   stop_trajectory_duration: 0        # Override default